backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "worksheet_library"
    label: "Worksheet Library"
    files:
      - label: "Worksheets"
        name: "worksheets"
        file: "content/worksheets.json"
        fields:
          - label: "Worksheets"
            name: "worksheets"
            widget: "list"
            summary: "Lesson {{fields.lesson}} - {{fields.title}}"
            fields:
              - { label: "Lesson Number", name: "lesson", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
              - { label: "Worksheet File", name: "file", widget: "string" }
